name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - run: |
          echo $ANDROID_SDK_ROOT
          ls $ANDROID_SDK_ROOT
      - name: Buck build
        uses: passy/run-buck@main
        with:
          commands: '/opt/android-sdk-linux/tools/bin/sdkmanager "build-tools;27.0.3"; buck fetch //...; buck build :soloader'
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
